service: url-shortener-go
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-better-credentials

params:
  dev:
    profile: main
    domain: go.aws.davidquennoz.com
    hostedZoneId: Z089474117N63KWACWF8R
    certificate: arn:aws:acm:us-east-1:381492255523:certificate/f4a8d005-c4ec-40e2-ba95-2e5ffbb5178a

provider:
  name: aws
  profile: ${param:profile}
  region: us-east-1
  deploymentMethod: direct
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: !GetAtt Table.Arn
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
  runtime: provided.al2023
  environment:
    TABLE: !Ref Table

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shortened_urls
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          PriceClass: PriceClass_100
          Aliases:
            - ${param:domain}
          ViewerCertificate:
            AcmCertificateArn: ${param:certificate}
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          Origins:
            - DomainName: !Join [".", [!Ref HttpApi, "execute-api", "${self:provider.region}", "amazonaws.com"]]
              Id: main-origin
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: false
            TargetOriginId: main-origin
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled managed policy
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader managed policy
            ViewerProtocolPolicy: redirect-to-https

    DNSRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name: ${param:domain}
        HostedZoneId: ${param:hostedZoneId}
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2 # This is always the HostedZoneId for CloudFront distributions

package:
  patterns:
    - "!**"
    - "bootstrap"

functions:
  main:
    handler: bootstrap
    memorySize: 512
    timeout: 5
    events:
      - httpApi: "*"
